language: node_js

sudo: false

node_js:
  - '5.5'
  - '5.0'
  - '4.1'
  - '4.0'
  - iojs

cache:
  directories:
    - "node_modules"

jdk:
  - openjdk7

before_deploy:
  - npm run compile
  - sed -i -e "/\/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz --prefix=package/ -o ${TRAVIS_TAG}-compiled.tar.gz HEAD

deploy:
  - provider: releases
    api_key:
      secure: NReNxZYQ0IO5O/1axCc81WjrPZtIbL0iXCxm3YqE9N5UaNbEGPqCoHjrcMRu2WfCrDclNx/OJ286lq0U/XoY5AkKV9D/ENh2I+vHSNesM1v/3+GsNDbypFjebpgnkFPgut0hQMea/mZeJO8Y7dgfDJqb8uT8gc6GsNPD+SXWUWw=
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      repo: hiroaki-yamamoto/node-validator-nu
      tags: true
  - provider: npm
    email: admin@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: nO9LdBsCzwF/lvTQJ6zyuZTlhk85iGN5zftoHoNvQVGXbPvR8Qb9yZNyzz+X2svPagouloRJ952zu+XXnlG9J3SdcYa9283bGQLXVcKxmCrSzTnrPhRz+oCCebTGpEjZtz7FXu6+LHjxX5JhLF7OmovOUv309d33t+u6KYtodcI=
    on:
      tags: true
