language: node_js
sudo: false

node_js:
    - "0.12"
    - "0.11"
    - "0.10"
    - "iojs"

jdk:
    - "openjdk7"

after_success:
  - "npm prepublish"

deploy:
  provider: releases
  api-key: 4e26c8d19e4278418b9b3ed67950dadf2c77e0ae
  skip_cleanup: true
  on:
    branch: master
    tags: true
