language: node_js
sudo: false

node_js:
    - "0.12"
    - "0.11"
    - "0.10"
    - "iojs"

jdk:
    - "openjdk7"

after_success:
  - "npm prepublish"

deploy:
  provider: releases
  api_key: 5fa770d40bb0f73ab43befa2d65bfbe7db81bcc8
  skip_cleanup: true
  on:
    branch: master
    tags: true

after_deploy:
  - "npm publish"
